[build]
  publish = "src/pages"
  command = "npm run build"

[build.environment]
  PUBLIC_BACKEND_URL = "https://your-backend-service.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.astro"
  status = 200
